// src/data.ts
import type { HappyElement, CategoryDef, TypeDef } from "./types";

export const elements: HappyElement[] = [
  // --- ROW 1 (Level 5 - Top) ---
  {
    id: 1,
    name: "SET THE GOAL AND DO IT",
    type: "M/P",
    level: 5,
    category: "dopamine",
    icon: "goal.svg",
    row: 1,
    colStart: 1,
  },
  // Gap 2, 3
  {
    id: 2,
    name: "HUG SOMEONE",
    type: "H/M",
    level: 5,
    category: "oxytocin",
    icon: "hug.svg",
    row: 1,
    colStart: 4,
  },
  {
    id: 3,
    name: "MEET FRIENDS",
    type: "M",
    level: 5,
    category: "oxytocin",
    icon: "friends.svg",
    row: 1,
    colStart: 5,
  },
  {
    id: 4,
    name: "MEDITATION",
    type: "M",
    level: 5,
    category: "serotonin",
    icon: "meditate.svg",
    row: 1,
    colStart: 6,
  },
  {
    id: 5,
    name: "SUNBATHING",
    type: "H/M",
    level: 5,
    category: "serotonin",
    icon: "sun.svg",
    row: 1,
    colStart: 7,
  },
  {
    id: 6,
    name: "EXERCISE",
    type: "P",
    level: 5,
    category: "serotonin",
    icon: "exercise.svg",
    row: 1,
    colStart: 8,
  },
  // Gap 9, 10, 11
  {
    id: 7,
    name: "SPICY FOODS",
    type: "F",
    level: 5,
    category: "endorphins",
    icon: "spicy.svg",
    row: 1,
    colStart: 12,
  },

  // --- ROW 2 (Level 4) ---
  {
    id: 8,
    name: "SLEEP",
    type: "M",
    level: 4,
    category: "dopamine",
    icon: "sleep.svg",
    row: 2,
    colStart: 1,
  },
  {
    id: 9,
    name: "BANANA",
    type: "F",
    level: 4,
    category: "dopamine",
    icon: "banana.svg",
    row: 2,
    colStart: 2,
  },
  {
    id: 10,
    name: "LISTEN TO MUSIC",
    type: "M",
    level: 4,
    category: "oxytocin",
    icon: "music.svg",
    row: 2,
    colStart: 3,
  },
  {
    id: 11,
    name: "MILK",
    type: "F",
    level: 4,
    category: "oxytocin",
    icon: "milk.svg",
    row: 2,
    colStart: 4,
  },
  {
    id: 12,
    name: "EGG",
    type: "F",
    level: 4,
    category: "serotonin",
    icon: "egg.svg",
    row: 2,
    colStart: 5,
  },
  {
    id: 13,
    name: "GREEN TEA",
    type: "F",
    level: 4,
    category: "serotonin",
    icon: "greentea.svg",
    row: 2,
    colStart: 6,
  },
  {
    id: 14,
    name: "SALMON",
    type: "F",
    level: 4,
    category: "serotonin",
    icon: "salmon.svg",
    row: 2,
    colStart: 7,
  },
  {
    id: 15,
    name: "SEEDS",
    type: "F",
    level: 4,
    category: "serotonin",
    icon: "seeds.svg",
    row: 2,
    colStart: 8,
  },
  {
    id: 16,
    name: "TAKE A COLD SHOWER",
    type: "H",
    level: 4,
    category: "serotonin",
    icon: "shower.svg",
    row: 2,
    colStart: 9,
  },
  {
    id: 17,
    name: "DARK CHOCOLATE",
    type: "F",
    level: 4,
    category: "endorphins",
    icon: "choco.svg",
    row: 2,
    colStart: 10,
  },
  {
    id: 18,
    name: "PATATO",
    type: "M",
    level: 4,
    category: "endorphins",
    icon: "potato.svg",
    row: 2,
    colStart: 11,
  },
  {
    id: 19,
    name: "STRETCHING",
    type: "M",
    level: 4,
    category: "endorphins",
    icon: "stretch.svg",
    row: 2,
    colStart: 12,
  },

  // --- ROW 3 (Level 3) ---
  {
    id: 20,
    name: "APPLE",
    type: "F",
    level: 3,
    category: "dopamine",
    icon: "apple.svg",
    row: 3,
    colStart: 2,
  },
  {
    id: 21,
    name: "STRAWBERRY",
    type: "F",
    level: 3,
    category: "dopamine",
    icon: "strawberry.svg",
    row: 3,
    colStart: 3,
  },
  {
    id: 22,
    name: "GREEN VEGETABLES",
    type: "N",
    level: 3,
    category: "dopamine",
    icon: "green-veg.svg",
    row: 3,
    colStart: 4,
  },
  {
    id: 23,
    name: "AVOCADO",
    type: "F",
    level: 3,
    category: "oxytocin",
    icon: "avocado.svg",
    row: 3,
    colStart: 5,
  },
  {
    id: 24,
    name: "GREEN TEA",
    type: "F",
    level: 3,
    category: "oxytocin",
    icon: "greentea.svg",
    row: 3,
    colStart: 6,
  },
  {
    id: 25,
    name: "VITAMINC",
    type: "F",
    level: 3,
    category: "oxytocin",
    icon: "vitaminc.svg",
    row: 3,
    colStart: 7,
  },
  {
    id: 26,
    name: "CAULIFLOWER",
    type: "F",
    level: 3,
    category: "oxytocin",
    icon: "cauliflower.svg",
    row: 3,
    colStart: 8,
  },
  {
    id: 27,
    name: "GREEN VEGETABLES",
    type: "F",
    level: 3,
    category: "serotonin",
    icon: "green-veg-2.svg",
    row: 3,
    colStart: 9,
  },
  {
    id: 28,
    name: "TOMATO",
    type: "N",
    level: 3,
    category: "serotonin",
    icon: "tomato.svg",
    row: 3,
    colStart: 10,
  },
  {
    id: 29,
    name: "ENTERTAINMENT",
    type: "M",
    level: 3,
    category: "endorphins",
    icon: "entertainment.svg",
    row: 3,
    colStart: 11,
  },
  {
    id: 30,
    name: "CREAM",
    type: "F",
    level: 3,
    category: "endorphins",
    icon: "cream.svg",
    row: 3,
    colStart: 12,
  },

  // --- ROW 4 (Level 2) ---
  {
    id: 31,
    name: "BEANS",
    type: "F",
    level: 2,
    category: "dopamine",
    icon: "beans.svg",
    row: 4,
    colStart: 3,
  },
  {
    id: 32,
    name: "TOMATO",
    type: "N",
    level: 2,
    category: "dopamine",
    icon: "tomato.svg",
    row: 4,
    colStart: 4,
  },
  {
    id: 33,
    name: "CHIA SEEDS",
    type: "F",
    level: 2,
    category: "oxytocin",
    icon: "chiaseeds.svg",
    row: 4,
    colStart: 5,
  },
  {
    id: 34,
    name: "TOMATO",
    type: "F",
    level: 2,
    category: "oxytocin",
    icon: "tomato.svg",
    row: 4,
    colStart: 6,
  },
  {
    id: 35,
    name: "TOFU",
    type: "F",
    level: 2,
    category: "serotonin",
    icon: "tofu.svg",
    row: 4,
    colStart: 7,
  },
  {
    id: 36,
    name: "AVOCADO",
    type: "F",
    level: 2,
    category: "serotonin",
    icon: "avocado.svg",
    row: 4,
    colStart: 8,
  },
  {
    id: 37,
    name: "PACKETS",
    type: "F",
    level: 2,
    category: "endorphins",
    icon: "packets.svg",
    row: 4,
    colStart: 9,
  },
];

export const categories: CategoryDef[] = [
  {
    key: "dopamine",
    label: "DOPAMINE",
    colorClass: "border-yellow-400 text-yellow-600",
  },
  {
    key: "oxytocin",
    label: "OXYTOCIN",
    colorClass: "border-red-400 text-red-600",
  },
  {
    key: "serotonin",
    label: "SEROTONIN",
    colorClass: "border-green-400 text-green-600",
  },
  {
    key: "endorphins",
    label: "ENDORPHINS",
    colorClass: "border-purple-400 text-purple-600",
  },
];

export const types: TypeDef[] = [
  { key: "P", label: "PHYSICAL HABIT" },
  { key: "M", label: "MENTAL HABIT" },
  { key: "F", label: "FOOD" },
  // { key: "H", label: "HYGIENE" },
  // { key: "N", label: "NATURE" },
];