// src/data.ts
import type { HappyElement, CategoryDef, TypeDef } from "./types";

export const elements: HappyElement[] = [
  // --- ROW 1 (Level 5 - Top) ---
  {
    id: 1,
    name: "SET THE GOAL AND DO IT",
    type: "M/P",
    level: 5,
    category: "dopamine",
    icon: "goal.svg",
    row: 1,
    colStart: 1,
    recommendation: "Break big goals into small steps.",
    mainEffect: "Increases focus and satisfaction.",
  },
  {
    id: 2,
    name: "HUG SOMEONE",
    type: "M", // Updated from P/M
    level: 5,
    category: "oxytocin",
    icon: "hug.svg",
    row: 1,
    colStart: 4,
    recommendation: "Hug for 20+ seconds",
    mainEffect: "Rapid oxytocin boost → reduces anxiety",
  },
  {
    id: 3,
    name: "MEET FRIENDS",
    type: "M",
    level: 5,
    category: "oxytocin",
    icon: "friends.svg",
    row: 1,
    colStart: 5,
    recommendation: "1–2 gatherings per week",
    mainEffect: "Enhances social bonding and stress relief",
  },
  {
    id: 4,
    name: "MEDITATION",
    type: "M",
    level: 5,
    category: "serotonin",
    icon: "meditate.svg",
    row: 1,
    colStart: 6,
    recommendation: "10–20 minutes/day",
    mainEffect: "Increases inner safety and emotional balance",
  },
  {
    id: 5,
    name: "SUNBATHING",
    type: "M", // Updated from P/M
    level: 5,
    category: "serotonin",
    icon: "sun.svg",
    row: 1,
    colStart: 7,
    recommendation: "10–20 minutes/day",
    mainEffect: "Sunlight boosts oxytocin (and serotonin)",
  },
  {
    id: 6,
    name: "EXERCISE",
    type: "P",
    level: 5,
    category: "serotonin",
    icon: "exercise.svg",
    row: 1,
    colStart: 8,
    recommendation: "30 minutes, 3–5 times/week",
    mainEffect: "Strong and sustained serotonin activation",
  },
  {
    id: 7,
    name: "SPICY FOODS",
    type: "F",
    level: 5,
    category: "endorphins",
    icon: "spicy.svg",
    row: 1,
    colStart: 12,
    recommendation: "Occasionally, 1–2 times/week",
    mainEffect: "Capsaicin triggers endorphin release",
  },

  // --- ROW 2 (Level 4) ---
  {
    id: 8,
    name: "SLEEP",
    type: "M",
    level: 4,
    category: "dopamine",
    icon: "sleep.svg",
    row: 2,
    colStart: 1,
    recommendation: "7-8 hours/night",
    mainEffect: "Restores dopamine receptors",
  },
  {
    id: 9,
    name: "BANANA",
    type: "F",
    level: 4,
    category: "dopamine",
    icon: "banana.svg",
    row: 2,
    colStart: 2,
    recommendation: "1-2 bananas/day",
    mainEffect: "Rich in tyrosine (dopamine precursor)",
  },
  {
    id: 10,
    name: "LISTEN TO MUSIC",
    type: "M",
    level: 4,
    category: "oxytocin",
    icon: "music.svg",
    row: 2,
    colStart: 3,
    recommendation: "30 mins of favorite tunes",
    mainEffect: "Releases oxytocin and reduces cortisol",
  },
  {
    id: 11,
    name: "MILK",
    type: "F",
    level: 4,
    category: "oxytocin",
    icon: "milk.svg",
    row: 2,
    colStart: 4,
    recommendation: "200–250ml/day", // Updated
    mainEffect: "Calming peptides support oxytocin",
  },
  {
    id: 12,
    name: "EGG",
    type: "F",
    level: 4,
    category: "serotonin",
    icon: "egg.svg",
    row: 2,
    colStart: 5,
    recommendation: "50–100g/day", // Updated
    mainEffect: "Protein & vitamins support hormone regulation",
  },
  {
    id: 13,
    name: "GREEN TEA",
    type: "F",
    level: 4,
    category: "serotonin",
    icon: "greentea.svg",
    row: 2,
    colStart: 6,
    recommendation: "1–2 cups/day",
    mainEffect: "L-theanine has a calming effect on the brain",
  },
  {
    id: 14,
    name: "SALMON",
    type: "F",
    level: 4,
    category: "serotonin",
    icon: "salmon.svg",
    row: 2,
    colStart: 7,
    recommendation: "90–120g per serving", // Updated
    mainEffect: "Omega-3 strengthens serotonin signaling",
  },
  {
    id: 15,
    name: "SEEDS",
    type: "F",
    level: 4,
    category: "serotonin",
    icon: "seeds.svg",
    row: 2,
    colStart: 8,
    recommendation: "10–20g/day", // Updated
    mainEffect: "High in tryptophan → serotonin precursor",
  },
  {
    id: 16,
    name: "TAKE A COLD SHOWER",
    type: "P/M", // Updated
    level: 4,
    category: "serotonin", // Note: Your input lists this, but keep checking if it belongs to Endorphins (original data) or Serotonin. Kept original category, updated stats.
    icon: "shower.svg",
    row: 2,
    colStart: 9,
    recommendation: "5 minutes", // Updated from 30-60s
    mainEffect: "Sudden cold exposure triggers strong endorphin release",
  },
  {
    id: 17,
    name: "DARK CHOCOLATE",
    type: "F",
    level: 4,
    category: "endorphins",
    icon: "choco.svg",
    row: 2,
    colStart: 10,
    recommendation: "10–20g/day",
    mainEffect: "Theobromine stimulates endorphins & relaxation",
  },
  {
    id: 18,
    name: "POTATO", // Fixed Typo
    type: "F",
    level: 4,
    category: "endorphins",
    icon: "potato.svg",
    row: 2,
    colStart: 11,
    recommendation: "10–30g/day", // Updated
    mainEffect: "Carbohydrates stimulate endorphin release",
  },
  {
    id: 19,
    name: "STRETCHING",
    type: "P", // Updated from M
    level: 4,
    category: "endorphins",
    icon: "stretch.svg",
    row: 2,
    colStart: 12,
    recommendation: "5–10 minutes/day",
    mainEffect: "Relieves muscle tension → reduces pain → endorphins",
  },

  // --- ROW 3 (Level 3) ---
  {
    id: 20,
    name: "APPLE",
    type: "F",
    level: 3,
    category: "dopamine",
    icon: "apple.svg",
    row: 3,
    colStart: 2,
    recommendation: "1 apple/day",
    mainEffect: "Provides quercetin, protecting dopamine neurons",
  },
  {
    id: 21,
    name: "STRAWBERRY",
    type: "F",
    level: 3,
    category: "dopamine",
    icon: "strawberry.svg",
    row: 3,
    colStart: 3,
    recommendation: "1 cup/day",
    mainEffect: "Rich in Vitamin C and antioxidants",
  },
  {
    id: 22,
    name: "GREEN VEGETABLES",
    type: "N", // Keep original type unless specified F
    level: 3,
    category: "dopamine",
    icon: "green-veg.svg",
    row: 3,
    colStart: 4,
    recommendation: "150–300g/day", // Updated
    mainEffect: "Magnesium & folate → serotonin support",
  },
  {
    id: 23,
    name: "AVOCADO",
    type: "F/M", // Updated based on input
    level: 3,
    category: "oxytocin",
    icon: "avocado.svg",
    row: 3,
    colStart: 5,
    recommendation: "70–100g/day", // Updated
    mainEffect: "Healthy fats → nourish nervous system and oxytocin",
  },
  {
    id: 24,
    name: "GREEN TEA",
    type: "F",
    level: 3,
    category: "oxytocin",
    icon: "greentea.svg",
    row: 3,
    colStart: 6,
    recommendation: "1–2 cups/day",
    mainEffect: "L-theanine promotes relaxation",
  },
  {
    id: 25,
    name: "VITAMIN C", // Fixed Typo
    type: "F",
    level: 3,
    category: "oxytocin",
    icon: "vitaminc.svg",
    row: 3,
    colStart: 7,
    recommendation: "1–2 fruits/day",
    mainEffect: "Enhances tryptophan absorption",
  },
  {
    id: 26,
    name: "CAULIFLOWER",
    type: "F",
    level: 3,
    category: "oxytocin",
    icon: "cauliflower.svg",
    row: 3,
    colStart: 8,
    recommendation: "150g/day", // Updated
    mainEffect: "Folate supports serotonin regulation",
  },
  {
    id: 27,
    name: "GREEN VEGETABLES",
    type: "F",
    level: 3,
    category: "serotonin",
    icon: "green-veg-2.svg",
    row: 3,
    colStart: 9,
    recommendation: "150–300g/day", // Updated
    mainEffect: "Essential minerals for mood stability",
  },
  {
    id: 28,
    name: "TOMATO",
    type: "F",
    level: 3,
    category: "serotonin",
    icon: "tomato.svg",
    row: 3,
    colStart: 10,
    recommendation: "1–2 tomatoes/day",
    mainEffect: "Lycopene protects the nervous system",
  },
  {
    id: 29,
    name: "ENTERTAINMENT (FUN CONTENT)", // Updated Name
    type: "M",
    level: 3,
    category: "endorphins",
    icon: "entertainment.svg",
    row: 3,
    colStart: 11,
    recommendation: "2–4 times/week",
    mainEffect: "Laughter boosts endorphins",
  },
  {
    id: 30,
    name: "CREAM",
    type: "F",
    level: 3,
    category: "endorphins",
    icon: "cream.svg",
    row: 3,
    colStart: 12,
    recommendation: "In small portions, 1–2 times/week",
    mainEffect: "Treat-reward effect → endorphins, stress relief",
  },

  // --- ROW 4 (Level 2) ---
  {
    id: 31,
    name: "BEANS",
    type: "F",
    level: 2,
    category: "dopamine",
    icon: "beans.svg",
    row: 4,
    colStart: 3,
    recommendation: "1/2 cup per serving",
    mainEffect: "Stabilizes blood sugar and mood",
  },
  {
    id: 32,
    name: "TOMATO",
    type: "F",
    level: 2,
    category: "dopamine",
    icon: "tomato.svg",
    row: 4,
    colStart: 4,
    recommendation: "1–2 tomatoes/day",
    mainEffect: "Antioxidants support brain health",
  },
  {
    id: 33,
    name: "CHIA SEEDS",
    type: "F",
    level: 2,
    category: "oxytocin",
    icon: "chiaseeds.svg",
    row: 4,
    colStart: 5,
    recommendation: "10–12g/day", // Updated
    mainEffect: "Omega-3 → supports oxytocin & brain health",
  },
  {
    id: 34,
    name: "TOMATO",
    type: "F",
    level: 2,
    category: "oxytocin",
    icon: "tomato.svg",
    row: 4,
    colStart: 6,
    recommendation: "Daily intake",
    mainEffect: "Supports overall hormonal balance",
  },
  {
    id: 35,
    name: "TOFU",
    type: "F",
    level: 2,
    category: "serotonin",
    icon: "tofu.svg",
    row: 4,
    colStart: 7,
    recommendation: "100–120g/day", // Updated
    mainEffect: "Plant protein & tryptophan",
  },
  {
    id: 36,
    name: "AVOCADO",
    type: "F",
    level: 2,
    category: "serotonin",
    icon: "avocado.svg",
    row: 4,
    colStart: 8,
    recommendation: "70–100g/day", // Updated
    mainEffect: "Healthy fats help regulate serotonin",
  },
  {
    id: 37,
    name: "PACKETS (SNACKS)", // Updated Name
    type: "F",
    level: 2,
    category: "endorphins",
    icon: "packets.svg",
    row: 4,
    colStart: 9,
    recommendation: "150–200g", // Updated (Quantity seems high for snacks, but kept as requested)
    mainEffect: "Indulgence increases endorphins but should not be overused",
  },
];

export const categories: CategoryDef[] = [
  { key: "dopamine", label: "DOPAMINE", colorClass: "border-yellow-400 text-yellow-600" },
  { key: "oxytocin", label: "OXYTOCIN", colorClass: "border-red-400 text-red-600" },
  { key: "serotonin", label: "SEROTONIN", colorClass: "border-green-400 text-green-600" },
  { key: "endorphins", label: "ENDORPHINS", colorClass: "border-purple-400 text-purple-600" },
];

export const types: TypeDef[] = [
  { key: "P", label: "PHYSICAL HABIT" },
  { key: "M", label: "MENTAL HABIT" },
  { key: "F", label: "FOOD" },
];